// <auto-generated />
using System;
using AppointmentApplication.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppointmentApplication.Infrastructure.Data.CountryMigrations
{
    [DbContext(typeof(CountryUsersDbContext))]
    partial class CountryUsersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppointmentApplication.Domain.Citizens.Citizen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("NationalId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Citizens", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BirthDate = new DateTime(1990, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ahmed",
                            Gender = 0,
                            LastName = "Ali",
                            MiddleName = "Mohammed",
                            NationalId = 1000000001L,
                            PhoneNumber = "0984306816"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BirthDate = new DateTime(1988, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Fatima",
                            Gender = 1,
                            LastName = "Yousef",
                            MiddleName = "Hassan",
                            NationalId = 1000000002L,
                            PhoneNumber = "0984306817"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BirthDate = new DateTime(1995, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Omar",
                            Gender = 0,
                            LastName = "Mahmoud",
                            MiddleName = "Khaled",
                            NationalId = 1000000003L,
                            PhoneNumber = "0984306818"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            BirthDate = new DateTime(1992, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Layla",
                            Gender = 1,
                            LastName = "Abdel",
                            MiddleName = "Sami",
                            NationalId = 1000000004L,
                            PhoneNumber = "0984306819"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            BirthDate = new DateTime(1985, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Youssef",
                            Gender = 0,
                            LastName = "Hussein",
                            MiddleName = "Adel",
                            NationalId = 1000000005L,
                            PhoneNumber = "0984306820"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            BirthDate = new DateTime(1991, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mariam",
                            Gender = 1,
                            LastName = "Saeed",
                            MiddleName = "Tarek",
                            NationalId = 1000000006L,
                            PhoneNumber = "0984306821"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            BirthDate = new DateTime(1989, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ali",
                            Gender = 0,
                            LastName = "Nabil",
                            MiddleName = "Mostafa",
                            NationalId = 1000000007L,
                            PhoneNumber = "0984306822"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            BirthDate = new DateTime(1994, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sara",
                            Gender = 1,
                            LastName = "Fahmy",
                            MiddleName = "Omar",
                            NationalId = 1000000008L,
                            PhoneNumber = "0984306823"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            BirthDate = new DateTime(1993, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Hassan",
                            Gender = 0,
                            LastName = "Kamal",
                            MiddleName = "Ibrahim",
                            NationalId = 1000000009L,
                            PhoneNumber = "0984306824"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BirthDate = new DateTime(1990, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Noor",
                            Gender = 1,
                            LastName = "Salah",
                            MiddleName = "Yahya",
                            NationalId = 1000000010L,
                            PhoneNumber = "0984306825"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
